# Generated by Django 5.0.6 on 2024-06-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='LMS.estudiante'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesores',
            field=models.ManyToManyField(blank=True, to='LMS.profesor'),
        ),
    ]
