# Generated by Django 5.0.6 on 2024-07-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='autor',
        ),
        migrations.AlterField(
            model_name='foro',
            name='asignatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foro', to='LMS.asignatura'),
        ),
    ]
