# Generated by Django 5.0.6 on 2024-07-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_remove_foro_autor_alter_foro_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='fecha_creacion',
        ),
    ]
