# Generated by Django 5.0.6 on 2024-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_reunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
