# Generated by Django 5.0.6 on 2024-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_reunion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='plataforma',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('otra', 'Otra')], max_length=50),
        ),
    ]
