# Generated by Django 5.0.6 on 2024-07-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_alter_reunion_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjuntoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_tareas/')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='LMS.tarea')),
            ],
        ),
    ]
