# Generated by Django 5.0.6 on 2024-07-05 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_archivoadjuntotarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='LMS.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='CorreccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('comentario', models.CharField(max_length=1000, null=True)),
                ('corrector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.profesor')),
                ('entrega', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correccion', to='LMS.entrega')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjuntoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_entregas/')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='LMS.entrega')),
            ],
        ),
    ]
