# Generated by Django 5.0.6 on 2024-07-05 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_entrega_correccionentrega_archivoadjuntoentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 5, 9, 48, 3, 361330, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
