# Generated by Django 5.0.6 on 2024-07-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_entrega_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='comentario',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='archivoadjuntoentrega',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos_entregas/'),
        ),
    ]
