# Generated by Django 5.0.6 on 2024-07-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_entrega_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='puntual',
            field=models.BooleanField(default=True),
        ),
    ]
